filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: https://kibana:5601
  username: elastic
  password: elastic

output.elasticsearch:
  hosts: https://es01:9200
  username: elastic
  password: elastic
  ssl:
    enabled: true
    certificate_authorities: certs/ca/ca.crt