metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: https://es01:9200
  username: elastic
  password: elastic
  ssl:
    enabled: true
    certificate_authorities: certs/ca/ca.crt

- module: kibana
  metricsets: 
    - stats
  period: 10s
  hosts: https://kibana:5601
  username: elastic
  password: elastic
  xpack.enabled: true
  ssl:
    enabled: true
    certificate_authorities: certs/ca/ca.crt

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: https://es01:9200
  username: elastic
  password: elastic
  ssl:
    enabled: true
    certificate_authorities: certs/ca/ca.crt